# Generated by Django 3.2.7 on 2021-11-30 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('target_price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('relation', models.CharField(choices=[('<', 'Less Than'), ('>', 'Greater Than'), ('=', 'Equals')], default='=', max_length=1)),
                ('completed', models.BooleanField(default=False)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin.coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
