# Generated by Django 3.2.7 on 2021-11-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='relation',
            field=models.CharField(choices=[('>=', 'Increases By'), ('<=', 'Decreases By'), ('=', 'Equals')], default='=', max_length=2),
        ),
    ]
